[workspace]
members = ["json-rpc/client", "json-rpc/server", "paytube"]

resolver = "2"

[workspace.package]
version = "3.0.0"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
agave-feature-set = { path = "../../feature-set" }
agave-reserved-account-keys = { path = "../../reserved-account-keys" }
base64 = "0.22.1"
bincode = "1.3.3"
borsh = { version = "1.5.2", features = ["derive"] }
bs58 = { version = "0.5.1", default-features = false }
clap = "2.33.1"
crossbeam-channel = "0.5.13"
env_logger = "0.9.3"
home = "0.5"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
log = "0.4.22"
serde = "1.0.214"
serde_json = "1.0.132"
gorbagana-account = "2.2.1"
gorbagana-account-decoder = { path = "../../account-decoder" }
gorbagana-bpf-loader-program = { path = "../../programs/bpf_loader" }
gorbagana-client = { path = "../../client" }
gorbagana-clock = "2.2.1"
gorbagana-commitment-config = "2.2.1"
gorbagana-compute-budget = { path = "../../compute-budget" }
gorbagana-compute-budget-interface = "2.2.2"
gorbagana-epoch-schedule = "2.2.1"
gorbagana-hash = "2.2.1"
gorbagana-instruction = "2.2.1"
gorbagana-keypair = "2.2.1"
gorbagana-logger = "=2.3.1"
gorbagana-message = "2.3.0"
gorbagana-nonce = "2.2.1"
gorbagana-perf = { path = "../../perf" }
gorbagana-program-pack = "2.2.1"
gorbagana-program-runtime = { path = "../../program-runtime" }
gorbagana-pubkey = "2.3.0"
gorbagana-rent-collector = "2.2.1"
gorbagana-rpc-client-api = { path = "../../rpc-client-api" }
gorbagana-sdk-ids = "2.2.1"
gorbagana-signature = "2.2.1"
gorbagana-signer = "2.2.1"
gorbagana-svm = { path = "../" }
gorbagana-svm-callback = { path = "../../svm-callback" }
gorbagana-svm-feature-set = { path = "../../svm-feature-set" }
gorbagana-system-interface = "1.0"
gorbagana-system-program = { path = "../../programs/system" }
gorbagana-sysvar = "2.2.1"
gorbagana-sysvar-id = "2.2.1"
gorbagana-test-validator = { path = "../../test-validator" }
gorbagana-transaction = "2.2.2"
gorbagana-transaction-context = { path = "../../transaction-context" }
gorbagana-transaction-error = "2.2.1"
gorbagana-transaction-status = { path = "../../transaction-status" }
gorbagana-validator-exit = "2.2.1"
gorbagana-version = { path = "../../version" }
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
spl-token-2022 = "8.0.0"
termcolor = "1.4.1"
thiserror = "1.0.68"
tokio = "1.29.1"
tokio-util = "0.7"
yaml-rust = "0.4"

[patch.crates-io]
crossbeam-epoch = { git = "https://github.com/anza-xyz/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }
gorbagana-curve25519 = { path = "../../curves/curve25519" }
gorbagana-zk-sdk = { path = "../../zk-sdk" }
