[package]
name = "gorbagana-net-shaper"
description = "The gorbagana cluster network shaping tool"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "gorbagana-net-shaper"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
rand = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-logger = "=2.3.1"
