[package]
name = "gorbagana-remote-wallet"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-remote-wallet"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["linux-static-hidraw", "hidapi"]
linux-shared-hidraw = ["hidapi/linux-shared-hidraw"]
linux-shared-libusb = ["hidapi/linux-shared-libusb"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-static-libusb = ["hidapi/linux-static-libusb"]

[dependencies]
console = { workspace = true }
dialoguer = { workspace = true }
hidapi = { workspace = true, optional = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
qstring = { workspace = true }
semver = { workspace = true }
gorbagana-derivation-path = { workspace = true }
gorbagana-offchain-message = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["std"] }
gorbagana-signature = { workspace = true, features = ["std"] }
gorbagana-signer = { workspace = true }
thiserror = { workspace = true }
uriparse = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
