[package]
name = "gorbagana-ed25519-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
assert_matches = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
gorbagana-ed25519-program = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-precompile-error = { workspace = true }
gorbagana-program-test = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
