[package]
name = "agave-transaction-view"
description = "Agave TranactionView"
documentation = "https://docs.rs/agave-transaction-view"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = []

[dependencies]
gorbagana-hash = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-short-vec = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-svm-transaction = { workspace = true }

[dev-dependencies]
# See order-crates-for-publishing.py for using this unusual `path = "."`
agave-transaction-view = { path = ".", features = ["dev-context-only-utils"] }
bincode = { workspace = true }
criterion = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true, features = ["serde"] }
gorbagana-signature = { workspace = true, features = ["serde"] }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true, features = ["bincode"] }
gorbagana-transaction = { workspace = true, features = ["bincode"] }

[[bench]]
name = "bytes"
harness = false

[[bench]]
name = "transaction_view"
harness = false
