[package]
name = "gorbagana-rpc-client-types"
description = "Gorbagana RPC Client Types"
documentation = "https://docs.rs/gorbagana-rpc-client-types"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
base64 = { workspace = true }
bs58 = { workspace = true, features = ["std"] }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-decoder-client-types = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true, features = ["serde"] }
gorbagana-fee-calculator = { workspace = true, features = ["serde"] }
gorbagana-inflation = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status-client-types = { workspace = true }
gorbagana-version = { workspace = true }
spl-generic-token = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
const_format = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
