[package]
name = "gorbagana-timings"
description = "Gorbagana Execution Timings"
documentation = "https://docs.rs/gorbagana-timings"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
eager = { workspace = true }
enum-iterator = { workspace = true }
gorbagana-pubkey = { workspace = true }
