[package]
name = "gorbagana-local-cluster"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
dev-context-only-utils = []

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-client-traits = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-core = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hard-forks = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-pubsub-client = { workspace = true }
gorbagana-quic-client = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-shred-version = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-thin-client = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-turbine = { workspace = true }
gorbagana-validator-exit = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-interface = { workspace = true }
gorbagana-vote-program = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
gorbagana-core = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-download-utils = { workspace = true }
gorbagana-ledger = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-local-cluster = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
