[package]
name = "gorbagana-tls-utils"
description = "Gorbagana TLS utilities"
documentation = "https://docs.rs/gorbagana-tls-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
rustls = { workspace = true, features = ["ring"] }
gorbagana-keypair = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-signer = { workspace = true }
x509-parser = { workspace = true }

[lints]
workspace = true
