[package]
name = "gorbagana-vote"
description = "Gorbagana vote"
documentation = "https://docs.rs/gorbagana-vote"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_vote"

[features]
dev-context-only-utils = ["dep:rand", "dep:bincode"]
frozen-abi = ["dep:gorbagana-frozen-abi", "dep:gorbagana-frozen-abi-macro"]

[dependencies]
bincode = { workspace = true, optional = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
gorbagana-account = { workspace = true, features = ["bincode"] }
gorbagana-bincode = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-serialize-utils = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["bincode"] }
gorbagana-vote-interface = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["bincode"] }
gorbagana-vote-interface = { workspace = true, features = ["bincode", "dev-context-only-utils"] }
static_assertions = { workspace = true }

[lints]
workspace = true
