[package]
name = "gorbagana-bpf-loader-program"
description = "Gorbagana BPF loader"
documentation = "https://docs.rs/gorbagana-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_bpf_loader_program"

[features]
default = ["metrics"]
metrics = ["gorbagana-program-runtime/metrics"]
shuttle-test = [
    "gorbagana-type-overrides/shuttle-test",
    "gorbagana-program-runtime/shuttle-test",
    "gorbagana-sbpf/shuttle-test",
]
svm-internal = []

[dependencies]
bincode = { workspace = true }
libsecp256k1 = { workspace = true }
num-traits = { workspace = true }
qualifier_attr = { workspace = true }
scopeguard = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-info = { workspace = true }
gorbagana-big-mod-exp = { workspace = true }
gorbagana-bincode = { workspace = true }
gorbagana-blake3-hasher = { workspace = true }
gorbagana-bn254 = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-cpi = { workspace = true }
gorbagana-curve25519 = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keccak-hasher = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true, features = ["serde"] }
gorbagana-loader-v4-interface = { workspace = true, features = ["bincode"] }
gorbagana-log-collector = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-poseidon = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sbpf = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-secp256k1-recover = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-stable-layout = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["bincode"] }
gorbagana-type-overrides = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
gorbagana-bpf-loader-program = { path = ".", features = ["svm-internal"] }
gorbagana-epoch-rewards = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-last-restart-slot = { workspace = true }
gorbagana-program = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-rent = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "serialization"
harness = false

[[bench]]
name = "bpf_loader_upgradeable"
harness = false
