[package]
name = "gorbagana-sbf-rust-sysvar"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = { workspace = true }
gorbagana-account-info = { workspace = true }
gorbagana-define-syscall = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-instructions-sysvar = { workspace = true }
gorbagana-msg = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }
gorbagana-program-error = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-sysvar = { workspace = true }

[lints]
workspace = true
