[package]
name = "gorbagana-stake-program"
description = "Gorbagana Stake program"
documentation = "https://docs.rs/gorbagana-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_stake_program"

[dependencies]
agave-feature-set = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bincode = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-config-program-client = { workspace = true, features = ["serde"] }
gorbagana-genesis-config = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["sha2"] }
gorbagana-rent = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["bincode"] }
gorbagana-type-overrides = { workspace = true }
gorbagana-vote-interface = { workspace = true, features = ["bincode"] }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-epoch-rewards = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-vote-program = { workspace = true, default-features = false }
test-case = { workspace = true }

[[bench]]
name = "stake"
harness = false

[lints]
workspace = true
