[package]
name = "agave-precompiles"
description = "Gorbagana precompiled programs."
documentation = "https://docs.rs/agave-precompiles"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
agave-feature-set = { workspace = true }
bincode = { workspace = true }
digest = { workspace = true }
ed25519-dalek = { workspace = true }
libsecp256k1 = { workspace = true }
openssl = { workspace = true }
sha3 = { workspace = true }
gorbagana-ed25519-program = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-precompile-error = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-secp256k1-program = { workspace = true, features = ["serde"] }
gorbagana-secp256r1-program = { workspace = true, features = ["openssl-vendored"] }

[dev-dependencies]
bytemuck = { workspace = true }
hex = { workspace = true }
rand0-7 = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keccak-hasher = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-secp256k1-program = { workspace = true, features = ["bincode"] }

[lints]
workspace = true
