[package]
name = "gorbagana-rpc-client-api"
description = "Gorbagana Client Common Utilities"
documentation = "https://docs.rs/gorbagana-rpc-client-api"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { workspace = true }
jsonrpc-core = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["rustls-tls"] }
reqwest-middleware = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder-client-types = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-rpc-client-types = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status-client-types = { workspace = true }
thiserror = { workspace = true }
