[package]
name = "gorbagana-rpc"
description = "Gorbagana RPC"
documentation = "https://docs.rs/gorbagana-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_rpc"

[features]
dev-context-only-utils = ["gorbagana-rpc/dev-context-only-utils"]

[dependencies]
agave-feature-set = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-epoch-info = { workspace = true }
gorbagana-epoch-rewards-hasher = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-faucet = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-poh = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-program-pack = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-send-transaction-service = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-slot-history = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-storage-bigtable = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-validator-exit = { workspace = true }
gorbagana-version = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-program = { workspace = true }
spl-generic-token = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
agave-reserved-account-keys = { workspace = true }
serial_test = { workspace = true }
gorbagana-address-lookup-table-interface = { workspace = true }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-fee-structure = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-nonce = { workspace = true }
gorbagana-nonce-account = { workspace = true }
gorbagana-program-option = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rent-debits = { workspace = true }
gorbagana-rpc = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-runtime-transaction = { workspace = true, features = [
    "dev-context-only-utils",
] }
gorbagana-sdk-ids = { workspace = true }
gorbagana-send-transaction-service = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-vote-interface = { workspace = true }
spl-pod = { workspace = true }
symlink = { workspace = true }
test-case = { workspace = true }
