[package]
name = "agave-reserved-account-keys"
description = "Reserved Gorbagana account keys"
documentation = "https://docs.rs/agave-reserved-account-keys"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
frozen-abi = ["dep:gorbagana-frozen-abi", "dep:gorbagana-frozen-abi-macro"]

[dependencies]
agave-feature-set = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-pubkey = { workspace = true, default-features = false }
gorbagana-sdk-ids = { workspace = true }

[dev-dependencies]
gorbagana-message = { workspace = true }
gorbagana-sysvar = { workspace = true }

[lints]
workspace = true
