[package]
name = "gorbagana-sbf-rust-curve25519"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
gorbagana-curve25519 = { workspace = true }
gorbagana-msg = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }

[lints]
workspace = true
