[package]
name = "gorbagana-geyser-plugin-manager"
description = "The Gorbagana Geyser plugin manager."
documentation = "https://docs.rs/gorbagana-geyser-plugin-manager"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
agave-geyser-plugin-interface = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
json5 = { workspace = true }
jsonrpc-core = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
