[package]
name = "gorbagana-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-faucet = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-version = { workspace = true }

[dev-dependencies]
gorbagana-core = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-hash = { workspace = true }
gorbagana-local-cluster = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
