[package]
name = "gorbagana-thin-client"
description = "Gorbagana Thin Client"
documentation = "https://docs.rs/gorbagana-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-client-traits = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-epoch-info = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true, features = ["bincode"] }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }

[dev-dependencies]
gorbagana-logger = { workspace = true }
