[package]
name = "gorbagana-entry"
description = "Gorbagana Entry"
documentation = "https://docs.rs/gorbagana-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_entry"

[dependencies]
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
dlopen2 = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-merkle-tree = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }

[dev-dependencies]
agave-reserved-account-keys = { workspace = true }
assert_matches = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-perf = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["verify"] }

[[bench]]
name = "entry_sigverify"
