[package]
name = "agave-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/agave-validator"
default-run = "agave-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
agave-geyser-plugin-interface = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-cli-output = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-core = { workspace = true }
gorbagana-download-utils = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-faucet = { workspace = true }
gorbagana-genesis-utils = { workspace = true }
gorbagana-geyser-plugin-manager = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-logger = "=2.3.1"
gorbagana-metrics = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-poh = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rpc = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-send-transaction-service = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-storage-bigtable = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-test-validator = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-turbine = { workspace = true }
gorbagana-unified-scheduler-pool = { workspace = true }
gorbagana-validator-exit = { workspace = true }
gorbagana-version = { workspace = true }
gorbagana-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[target.'cfg(not(any(target_env = "msvc", target_os = "freebsd")))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-program-option = { workspace = true }
gorbagana-program-pack = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-time-utils = { workspace = true }
spl-generic-token = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
