[package]
name = "gorbagana-log-collector"
description = "Gorbagana log collector"
documentation = "https://docs.rs/gorbagana-log-collector"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true }
