[package]
name = "gorbagana-runtime"
description = "Gorbagana runtime"
documentation = "https://docs.rs/gorbagana-runtime"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_runtime"

[features]
dev-context-only-utils = [
    "dep:gorbagana-system-program",
    "gorbagana-svm/dev-context-only-utils",
    "gorbagana-runtime-transaction/dev-context-only-utils",
    "gorbagana-vote/dev-context-only-utils",
]
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-account/frozen-abi",
    "gorbagana-accounts-db/frozen-abi",
    "gorbagana-compute-budget/frozen-abi",
    "gorbagana-cost-model/frozen-abi",
    "gorbagana-epoch-schedule/frozen-abi",
    "gorbagana-hard-forks/frozen-abi",
    "gorbagana-inflation/frozen-abi",
    "gorbagana-instruction/frozen-abi",
    "gorbagana-perf/frozen-abi",
    "gorbagana-program-runtime/frozen-abi",
    "gorbagana-rent/frozen-abi",
    "gorbagana-rent-collector/frozen-abi",
    "gorbagana-stake-interface/frozen-abi",
    "gorbagana-svm/frozen-abi",
    "gorbagana-transaction-error/frozen-abi",
    "gorbagana-version/frozen-abi",
    "gorbagana-vote/frozen-abi",
    "gorbagana-vote-program/frozen-abi",
]

[dependencies]
agave-feature-set = { workspace = true }
agave-precompiles = { workspace = true }
agave-reserved-account-keys = { workspace = true }
ahash = { workspace = true }
aquamarine = { workspace = true }
arrayref = { workspace = true }
assert_matches = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bv = { workspace = true, features = ["serde"] }
bytemuck = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true, features = ["rayon", "raw-api"] }
dir-diff = { workspace = true }
fnv = { workspace = true }
im = { workspace = true, features = ["rayon", "serde"] }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
lz4 = { workspace = true }
memmap2 = { workspace = true }
mockall = { workspace = true }
modular-bitfield = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
num_enum = { workspace = true }
percentage = { workspace = true }
qualifier_attr = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-info = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-address-lookup-table-interface = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-bucket-map = { workspace = true }
gorbagana-builtins = { workspace = true }
gorbagana-client-traits = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-compute-budget-instruction = { workspace = true }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-cost-model = { workspace = true }
gorbagana-cpi = { workspace = true }
gorbagana-ed25519-program = { workspace = true }
gorbagana-epoch-info = { workspace = true }
gorbagana-epoch-rewards-hasher = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-feature-gate-interface = { workspace = true }
gorbagana-fee = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-fee-structure = { workspace = true, features = ["serde"] }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-genesis-config = { workspace = true }
gorbagana-hard-forks = { workspace = true, features = ["serde"] }
gorbagana-hash = { workspace = true }
gorbagana-inflation = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true, features = ["seed-derivable"] }
gorbagana-lattice-hash = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true, features = ["bincode"] }
gorbagana-loader-v4-interface = { workspace = true, features = ["serde"] }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-nohash-hasher = { workspace = true }
gorbagana-nonce = { workspace = true }
gorbagana-nonce-account = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-precompile-error = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["metrics"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rent-collector = { workspace = true, features = ["serde"] }
gorbagana-rent-debits = { workspace = true }
gorbagana-reward-info = { workspace = true }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-secp256k1-program = { workspace = true }
gorbagana-seed-derivable = { workspace = true }
gorbagana-serde = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-slot-history = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-rent-collector = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-program = { workspace = true, optional = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["verify"] }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status-client-types = { workspace = true }
gorbagana-unified-scheduler-logic = { workspace = true }
gorbagana-version = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-interface = { workspace = true }
gorbagana-vote-program = { workspace = true }
spl-generic-token = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
symlink = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
agave-transaction-view = { workspace = true }
ed25519-dalek = { workspace = true }
libsecp256k1 = { workspace = true }
memoffset = { workspace = true }
rand0-7 = { package = "rand", version = "0.7" }
rand_chacha = { workspace = true }
gorbagana-accounts-db = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-builtins = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-logger = { workspace = true }
gorbagana-rent-debits = { workspace = true, features = ["dev-context-only-utils"] }
# See order-crates-for-publishing.py for using this unusual `path = "."`
gorbagana-runtime = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-runtime-transaction = { workspace = true, features = [
    "dev-context-only-utils",
] }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true, features = ["std"] }
gorbagana-svm = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "prioritization_fee_cache"

[lints]
workspace = true
