[package]
name = "gorbagana-merkle-tree"
description = "Gorbagana Merkle Tree"
documentation = "https://docs.rs/gorbagana-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_merkle_tree"

[dependencies]
fast-math = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
