[package]
name = "gorbagana-zk-elgamal-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-program-test = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-zk-sdk = { workspace = true }
