[package]
name = "gorbagana-tps-client"
description = "Blockchain, Rebuilt for Scale"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bank-client = ["dep:gorbagana-client-traits", "dep:gorbagana-runtime"]

[dependencies]
log = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-client-traits = { workspace = true, optional = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-epoch-info = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-client = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true, optional = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
tempfile = { workspace = true }
