[package]
name = "agave-feature-set"
description = "Gorbagana runtime feature declarations"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[features]
frozen-abi = ["dep:gorbagana-frozen-abi", "dep:gorbagana-frozen-abi-macro"]

[dependencies]
ahash = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-pubkey = { workspace = true, default-features = false }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }

[lints]
workspace = true
