[package]
name = "gorbagana-gossip"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-gossip"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "gorbagana-gossip"
path = "src/main.rs"

[features]
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-bloom/frozen-abi",
    "gorbagana-ledger/frozen-abi",
    "gorbagana-perf/frozen-abi",
    "gorbagana-runtime/frozen-abi",
    "gorbagana-short-vec/frozen-abi",
    "gorbagana-version/frozen-abi",
    "gorbagana-vote/frozen-abi",
    "gorbagana-vote-program/frozen-abi",
]

[dependencies]
agave-feature-set = { workspace = true }
arrayvec = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true, features = ["rayon"] }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
siphasher = { workspace = true }
gorbagana-bloom = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-clock = "=2.2.2"
gorbagana-connection-cache = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-epoch-schedule = "=2.2.1"
gorbagana-frozen-abi = { version = "=2.3.0", optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { version = "=2.2.1", optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = "=2.3.0"
gorbagana-keypair = "=2.2.1"
gorbagana-ledger = { workspace = true }
gorbagana-logger = "=2.3.1"
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-native-token = "=2.2.2"
gorbagana-net-utils = { workspace = true }
gorbagana-packet = "=2.2.1"
gorbagana-perf = { workspace = true }
gorbagana-pubkey = { version = "=2.4.0", features = ["rand"] }
gorbagana-quic-definitions = "=2.2.1"
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sanitize = "=2.2.1"
gorbagana-serde-varint = "=2.2.2"
gorbagana-sha256-hasher = "=2.2.1"
gorbagana-short-vec = "=2.2.1"
gorbagana-signature = { version = "=2.3.0", default-features = false }
gorbagana-signer = "=2.2.1"
gorbagana-streamer = { workspace = true }
gorbagana-time-utils = "=2.2.1"
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction = "=2.2.3"
gorbagana-version = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-program = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bs58 = { workspace = true }
criterion = { workspace = true }
num_cpus = { workspace = true }
rand0-7 = { workspace = true }
rand_chacha0-2 = { workspace = true }
serial_test = { workspace = true }
gorbagana-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-perf = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-signature = { version = "=2.3.0", features = ["rand"] }
gorbagana-system-transaction = { workspace = true }
gorbagana-vote-interface = { workspace = true }
static_assertions = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bench]]
name = "weighted_shuffle"
harness = false

[lints]
workspace = true
