[package]
name = "gorbagana-compute-budget-program"
description = "Gorbagana Compute Budget program"
documentation = "https://docs.rs/gorbagana-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_compute_budget_program"

[dependencies]
gorbagana-program-runtime = { workspace = true }
