[package]
name = "gorbagana-fee"
description = "Gorbagana fee calculation"
documentation = "https://docs.rs/gorbagana-fee"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
gorbagana-fee-structure = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
