[package]
name = "gorbagana-transaction-status"
description = "Gorbagana transaction status types"
documentation = "https://docs.rs/gorbagana-transaction-status"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
Inflector = { workspace = true }
agave-reserved-account-keys = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-address-lookup-table-interface = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-loader-v2-interface = { workspace = true, features = ["bincode"] }
gorbagana-loader-v3-interface = { workspace = true, features = ["bincode"] }
gorbagana-message = { workspace = true }
gorbagana-program-option = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-reward-info = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status-client-types = { workspace = true }
gorbagana-vote-interface = { workspace = true }
spl-associated-token-account = { workspace = true, features = ["no-entrypoint"] }
spl-memo = { workspace = true, features = ["no-entrypoint"] }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
spl-token-group-interface = { workspace = true }
spl-token-metadata-interface = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
spl-token-confidential-transfer-proof-extraction = { workspace = true }
