# This package only exists to avoid circular dependencies during cargo publish:
# gorbagana-bpf-loader-program -> gorbagana-program-test -> gorbagana-bpf-loader-program

[package]
name = "gorbagana-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true }
gorbagana-program-test = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
