[package]
name = "gorbagana-loader-v4-program"
description = "Gorbagana Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_loader_v4_program"

[features]
agave-unstable-api = []
shuttle-test = [
    "gorbagana-type-overrides/shuttle-test",
    "gorbagana-program-runtime/shuttle-test",
    "gorbagana-sbpf/shuttle-test",
]
svm-internal = []

[dependencies]
log = { workspace = true }
qualifier_attr = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bincode = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true, features = ["svm-internal"] }
gorbagana-instruction = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true }
gorbagana-loader-v4-interface = { workspace = true, features = ["serde"] }
gorbagana-log-collector = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sbpf = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-type-overrides = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-sysvar = { workspace = true }
