[package]
name = "gorbagana-sbf-rust-account-mem-deprecated"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
gorbagana-account-info = { workspace = true }
gorbagana-program = { workspace = true }
gorbagana-program-error = { workspace = true }
gorbagana-program-memory = { workspace = true }
gorbagana-pubkey = { workspace = true }

[lints]
workspace = true
