[package]
name = "gorbagana-program-runtime"
description = "Gorbagana program runtime"
documentation = "https://docs.rs/gorbagana-program-runtime"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_program_runtime"

[features]
dev-context-only-utils = []
dummy-for-ci-check = ["metrics"]
frozen-abi = ["dep:gorbagana-frozen-abi", "dep:gorbagana-frozen-abi-macro"]
metrics = ["dep:gorbagana-metrics"]
shuttle-test = ["gorbagana-type-overrides/shuttle-test", "gorbagana-sbpf/shuttle-test"]

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
percentage = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
gorbagana-account = { workspace = true, features = ["bincode"] }
gorbagana-clock = { workspace = true }
gorbagana-epoch-rewards = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-fee-structure = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-last-restart-slot = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true, optional = true }
gorbagana-program-entrypoint = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-sbpf = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-stable-layout = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-type-overrides = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
gorbagana-account-info = { workspace = true }
gorbagana-instruction = { workspace = true, features = ["bincode"] }
gorbagana-program-runtime = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-transaction-context = { workspace = true, features = [
    "dev-context-only-utils",
] }
test-case = { workspace = true }

[lints]
workspace = true
