# This package only exists to avoid circular dependencies during cargo publish:
# gorbagana-program-test <--> gorbagana-stake-program

[package]
name = "gorbagana-stake-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-program-error = { workspace = true }
gorbagana-program-test = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-vote-program = { workspace = true }
test-case = { workspace = true }
