[package]
name = "json-rpc-server"
description = "Reference example using Gorbagana SVM API for RPC API"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
env_logger = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-nonce = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-program = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-validator-exit = { workspace = true }
gorbagana-version = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }
