[package]
name = "gorbagana-udp-client"
description = "Gorbagana UDP Client"
documentation = "https://docs.rs/gorbagana-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-transaction-error = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
gorbagana-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-packet = { workspace = true }
