[package]
name = "agave-store-tool"
description = "Tool for account storage files"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = []

[dependencies]
ahash = { workspace = true }
clap = { workspace = true }
rayon = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-accounts-db = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-version = { workspace = true }
