[package]
name = "gorbagana-sbf-rust-poseidon"
description = "Gorbagana SBF test program written in Rust"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
array-bytes = { workspace = true }
gorbagana-msg = { workspace = true }
gorbagana-poseidon = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }

[lints]
workspace = true
