[package]
name = "gorbagana-unified-scheduler-pool"
description = "The Gorbagana unified scheduler pool"
documentation = "https://docs.rs/gorbagana-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = []

[dependencies]
agave-banking-stage-ingress-types = { workspace = true }
aquamarine = { workspace = true }
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
derive-where = { workspace = true }
derive_more = { workspace = true }
dyn-clone = { workspace = true }
log = { workspace = true }
qualifier_attr = { workspace = true }
scopeguard = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-cost-model = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-poh = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-unified-scheduler-logic = { workspace = true }
static_assertions = { workspace = true }
trait-set = { workspace = true }
unwrap_none = { workspace = true }
vec_extract_if_polyfill = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-system-transaction = { workspace = true }
test-case = { workspace = true }
