[package]
name = "gorbagana-genesis"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-genesis"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "gorbagana_genesis"

[[bin]]
name = "gorbagana-genesis"
path = "src/main.rs"

[dependencies]
agave-feature-set = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
gorbagana-account = "=2.2.1"
gorbagana-accounts-db = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-clock = "=2.2.2"
gorbagana-commitment-config = "=2.2.1"
gorbagana-entry = { workspace = true }
gorbagana-epoch-schedule = "=2.2.1"
gorbagana-feature-gate-interface = "=2.2.2"
gorbagana-fee-calculator = "=2.2.1"
gorbagana-genesis-config = "=2.3.0"
gorbagana-inflation = "=2.2.1"
gorbagana-keypair = "=2.2.1"
gorbagana-ledger = { workspace = true }
gorbagana-loader-v3-interface = "5.0.0"
gorbagana-logger = "=2.3.1"
gorbagana-native-token = "=2.2.2"
gorbagana-poh-config = "=2.2.1"
gorbagana-pubkey = { version = "=2.4.0", default-features = false }
gorbagana-rent = "=2.2.1"
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sdk-ids = "=2.2.1"
gorbagana-signer = "=2.2.1"
gorbagana-stake-interface = "=1.2.1"
gorbagana-stake-program = { workspace = true }
gorbagana-time-utils = "2.2.1"
gorbagana-version = { workspace = true }
gorbagana-vote-program = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
gorbagana-borsh = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
