[package]
name = "gorbagana-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-remote-wallet = { workspace = true, features = ["default"] }
gorbagana-rpc-client = { workspace = true, features = ["default"] }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-version = { workspace = true }

[dev-dependencies]
gorbagana-client-traits = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
