[package]
name = "agave-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/agave-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-cli-output = { workspace = true }
gorbagana-hash = "=2.3.0"
gorbagana-logger = "=2.3.1"
gorbagana-metrics = { workspace = true }
gorbagana-native-token = "=2.2.2"
gorbagana-notifier = { workspace = true }
gorbagana-pubkey = { version = "=2.4.0", default-features = false }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-version = { workspace = true }
