[package]
name = "gorbagana-zk-token-proof-program"
description = "Gorbagana Zk Token Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-zk-token-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
