[package]
name = "gorbagana-transaction-metrics-tracker"
description = "Gorbagana transaction metrics tracker"
documentation = "https://docs.rs/gorbagana-transaction-metrics-tracker"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
# Update this borsh dependency to the workspace version once
log = { workspace = true }
rand = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-short-vec = { workspace = true }
gorbagana-signature = { workspace = true }

[dev-dependencies]
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-packet = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-perf = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-system-transaction = { workspace = true }
