[package]
name = "gorbagana-genesis-utils"
description = "Gorbagana Genesis Utils"
documentation = "https://docs.rs/gorbagana-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_genesis_utils"

[dependencies]
log = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-download-utils = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-rpc-client = { workspace = true }
