[package]
name = "gorbagana-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true }
serde_derive = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-remote-wallet = { workspace = true, features = ["default"] }
gorbagana-rpc-client = { workspace = true, features = ["default"] }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-version = { workspace = true }
spl-associated-token-account = { version = "=7.0.0", features = ["no-entrypoint"] }
spl-token = { version = "=8.0.0", features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-test-validator = { workspace = true }
gorbagana-transaction-error = { workspace = true }
