[package]
name = "gorbagana-quic-client"
description = "Gorbagana Quic Client"
documentation = "https://docs.rs/gorbagana-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-lock = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-pubkey = { workspace = true, default-features = false }
gorbagana-quic-definitions = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-tls-utils = { workspace = true }
gorbagana-transaction-error = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-packet = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
