[package]
name = "gorbagana-perf"
description = "Gorbagana Performance APIs"
documentation = "https://docs.rs/gorbagana-perf"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "gorbagana_perf"

[features]
dev-context-only-utils = [
    "dep:gorbagana-clock",
    "dep:gorbagana-keypair",
    "dep:gorbagana-signer",
    "dep:gorbagana-system-interface",
    "dep:gorbagana-system-transaction",
    "dep:gorbagana-transaction",
    "dep:gorbagana-vote-program",
    "dep:gorbagana-vote",
]
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-short-vec/frozen-abi",
    "gorbagana-vote-program/frozen-abi",
]

[dependencies]
ahash = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
curve25519-dalek = { workspace = true }
dlopen2 = { workspace = true }
fnv = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
gorbagana-clock = { workspace = true, optional = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true, optional = true }
gorbagana-message = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-packet = { workspace = true, features = ["bincode"] }
gorbagana-pubkey = { workspace = true, default-features = false }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-short-vec = { workspace = true }
gorbagana-signature = { workspace = true, features = ["verify"] }
gorbagana-signer = { workspace = true, optional = true }
gorbagana-system-interface = { workspace = true, optional = true }
gorbagana-system-transaction = { workspace = true, optional = true }
gorbagana-time-utils = { workspace = true }
gorbagana-transaction = { workspace = true, optional = true }
gorbagana-vote = { workspace = true, optional = true }
gorbagana-vote-program = { workspace = true, optional = true }

[target."cfg(target_os = \"linux\")".dependencies]
caps = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["user"] }

[dev-dependencies]
assert_matches = { workspace = true }
rand_chacha = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-perf = { path = ".", features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[[bench]]
name = "sigverify"

[[bench]]
name = "discard"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(build_target_feature_avx)', 'cfg(build_target_feature_avx2)']
