[package]
name = "gorbagana-tpu-client-next"
description = "Client code to send transaction to TPU."
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
metrics = ["dep:gorbagana-metrics"]

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true, optional = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-tls-utils = { workspace = true }
gorbagana-tpu-client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
crossbeam-channel = { workspace = true }
futures = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
