[package]
name = "gorbagana-poh-bench"
documentation = "https://docs.rs/gorbagana-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-version = { workspace = true }
