[package]
name = "gorbagana-ledger"
description = "Gorbagana ledger"
documentation = "https://docs.rs/gorbagana-ledger"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_ledger"

[features]
dev-context-only-utils = []
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-runtime/frozen-abi",
]

[dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
anyhow = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
bitflags = { workspace = true, features = ["serde"] }
bzip2 = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true, features = ["rayon", "raw-api"] }
eager = { workspace = true }
fs_extra = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy-lru = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
mockall = { workspace = true }
num_cpus = { workspace = true }
num_enum = { workspace = true }
prost = { workspace = true }
qualifier_attr = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
reed-solomon-erasure = { workspace = true, features = ["simd-accel"] }
scopeguard = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-address-lookup-table-interface = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-cost-model = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-genesis-config = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["metrics"] }
gorbagana-pubkey = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-seed-derivable = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-shred-version = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-storage-bigtable = { workspace = true }
gorbagana-storage-proto = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-program = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
trees = { workspace = true }

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
version = "0.23.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
bs58 = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
gorbagana-account-decoder = { workspace = true }
# See order-crates-for-publishing.py for using this unusual `path = "."`
gorbagana-ledger = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-logger = { workspace = true }
gorbagana-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-perf = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-program-option = { workspace = true }
gorbagana-program-pack = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-signature = { workspace = true, features = ["rand"] }
gorbagana-vote = { workspace = true, features = ["dev-context-only-utils"] }
spl-generic-token = { workspace = true }
spl-pod = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "blockstore"

[[bench]]
name = "make_shreds_from_entries"
harness = false

[lints]
workspace = true
