[package]
name = "json-rpc-example-program"
version = "3.0.0"
edition = "2021"

[features]
# This was needed for ci
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
borsh = "0.9"
gorbagana-account-info = "2.3.0"
gorbagana-program-entrypoint = "2.3.0"
gorbagana-msg = "2.2.1"
gorbagana-pubkey = "2.4.0"

[lib]
name = "program"
crate-type = ["cdylib", "lib"]

[workspace]
