[package]
name = "gorbagana-storage-proto"
description = "Gorbagana Storage Protobuf Definitions"
documentation = "https://docs.rs/gorbagana-storage-proto"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_storage_proto"

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-serde = { workspace = true }
gorbagana-signature = { workspace = true, features = ["std"] }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["serde"] }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = { workspace = true }

[dev-dependencies]
enum-iterator = { workspace = true }
test-case = { workspace = true }
