[package]
name = "gorbagana-transaction-status-client-types"
description = "Core RPC client types for gorbagana-transaction-status"
documentation = "https://docs.rs/gorbagana-transaction-status-client-types"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder-client-types = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-reward-info = { workspace = true, features = ["serde"] }
gorbagana-signature = { workspace = true, default-features = false }
gorbagana-transaction = { workspace = true, features = ["serde"] }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
