[package]
name = "gorbagana-svm"
description = "Gorbagana SVM"
documentation = "https://docs.rs/gorbagana-svm"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_svm"

[features]
dev-context-only-utils = ["dep:qualifier_attr"]
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-program-runtime/frozen-abi",
]
shuttle-test = [
    "gorbagana-type-overrides/shuttle-test",
    "gorbagana-program-runtime/shuttle-test",
    "gorbagana-bpf-loader-program/shuttle-test",
    "gorbagana-loader-v4-program/shuttle-test",
]
svm-internal = []

[dependencies]
ahash = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
percentage = { workspace = true }
qualifier_attr = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-fee-structure = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true, features = ["std"] }
gorbagana-instructions-sysvar = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true, features = ["bincode"] }
gorbagana-loader-v4-interface = { workspace = true }
gorbagana-loader-v4-program = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-nonce = { workspace = true }
gorbagana-nonce-account = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }
gorbagana-program-pack = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["metrics"] }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rent-collector = { workspace = true }
gorbagana-rent-debits = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-svm-rent-collector = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["debug-signature"] }
gorbagana-transaction-error = { workspace = true }
gorbagana-type-overrides = { workspace = true }
spl-generic-token = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
ed25519-dalek = { workspace = true }
libsecp256k1 = { workspace = true }
openssl = { workspace = true }
prost = { workspace = true }
rand0-7 = { workspace = true }
shuttle = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-compute-budget-instruction = { workspace = true }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-compute-budget-program = { workspace = true }
gorbagana-ed25519-program = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-precompile-error = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = [ "rand" ] }
gorbagana-rent = { workspace = true }
gorbagana-sbpf = { workspace = true }
gorbagana-secp256k1-program = { workspace = true }
gorbagana-secp256r1-program = { workspace = true, features = ["openssl-vendored"] }
gorbagana-signature = { workspace = true, features = [ "rand" ] }
gorbagana-signer = { workspace = true }
# See order-crates-for-publishing.py for using this unusual `path = "."`
gorbagana-svm = { path = ".", features = ["dev-context-only-utils", "svm-internal"] }
gorbagana-svm-conformance = { workspace = true }
gorbagana-system-program = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
spl-token = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
