[package]
name = "gorbagana-turbine"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/gorbagana-turbine"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
agave-xdp = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy-lru = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
quinn = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
rustls = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-cluster-type = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-poh = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-client = { workspace = true }
gorbagana-rayon-threadlimit = { workspace = true }
gorbagana-rpc = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-tls-utils = { workspace = true }
gorbagana-transaction-error = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
caps = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bs58 = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-transaction = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "cluster_info"

[[bench]]
name = "cluster_nodes"
