[package]
name = "gorbagana-wen-restart"
description = "Automatic repair and restart protocol"
documentation = "https://github.com/gorbagana-foundation/gorbagana-improvement-documents/pull/46"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "gorbagana_wen_restart"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rayon = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-shred-version = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-interface = { workspace = true }
gorbagana-vote-program = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
tempfile = { workspace = true }
