[package]
name = "gorbagana-faucet"
description = "Gorbagana Faucet"
documentation = "https://docs.rs/gorbagana-faucet"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_faucet"

[[bin]]
name = "gorbagana-faucet"
path = "src/bin/faucet.rs"

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-config = { workspace = true }
gorbagana-hash = "=2.3.0"
gorbagana-instruction = "=2.3.0"
gorbagana-keypair = "=2.2.1"
gorbagana-logger = "=2.3.1"
gorbagana-message = "=2.4.0"
gorbagana-metrics = { workspace = true }
gorbagana-native-token = "=2.2.2"
gorbagana-packet = "=2.2.1"
gorbagana-pubkey = { version = "=2.4.0", features = ["rand"] }
gorbagana-signer = "=2.2.1"
gorbagana-system-interface = "=1.0"
gorbagana-system-transaction = "=2.2.1"
gorbagana-transaction = "=2.2.3"
gorbagana-version = { workspace = true }
spl-memo = { version = "=6.0.0", features = ["no-entrypoint"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
