[package]
name = "gorbagana-svm-rent-collector"
description = "Gorbagana SVM Rent Collector"
documentation = "https://docs.rs/gorbagana-svm-rent-collector"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
gorbagana-account = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rent-collector = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }

[dev-dependencies]
gorbagana-epoch-schedule = { workspace = true }
