[package]
name = "agave-geyser-plugin-interface"
description = "The Gorbagana Geyser plugin interface."
documentation = "https://docs.rs/agave-geyser-plugin-interface"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true, features = ["std"] }
gorbagana-clock = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-status = { workspace = true }
thiserror = { workspace = true }
