[package]
name = "gorbagana-sbf-rust-realloc-dep"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
gorbagana-instruction = { workspace = true }
gorbagana-pubkey = { workspace = true }

[lib]
crate-type = ["lib"]
