[package]
name = "gorbagana-transaction-context"
description = "Gorbagana data shared between program runtime and built-in programs as well as SBF programs."
documentation = "https://docs.rs/gorbagana-transaction-context"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde", "gorbagana-account/bincode"]
debug-signature = ["dep:gorbagana-signature"]
dev-context-only-utils = [
    "bincode",
    "debug-signature",
    "gorbagana-account/dev-context-only-utils",
]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
gorbagana-account = { workspace = true }
gorbagana-instruction = { workspace = true, features = ["std"] }
gorbagana-instructions-sysvar = { workspace = true }
gorbagana-pubkey = { workspace = true }

[target.'cfg(not(target_os = "gorbagana"))'.dependencies]
bincode = { workspace = true, optional = true }
gorbagana-rent = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true, optional = true }

[dev-dependencies]
gorbagana-account-info = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction-context = { path = ".", features = [
    "dev-context-only-utils",
] }
static_assertions = { workspace = true }

[lints]
workspace = true
