[package]
name = "gorbagana-svm-callback"
version = "3.0.0"
description = "Gorbagana SVM callback"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[dependencies]
gorbagana-account = { workspace = true }
gorbagana-precompile-error = { workspace = true }
gorbagana-pubkey = { workspace = true }

[lints]
workspace = true
