[package]
name = "gorbagana-tpu-client"
description = "Gorbagana TPU Client"
documentation = "https://docs.rs/gorbagana-tpu-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["spinner"]
# Support tpu-client methods that feature a spinner progress bar for
# command-line interfaces
spinner = [
    "dep:indicatif",
    "dep:gorbagana-message",
    "gorbagana-rpc-client/spinner",
]

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true, optional = true }
log = { workspace = true }
rayon = { workspace = true }
gorbagana-client-traits = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-epoch-info = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true, optional = true }
gorbagana-net-utils = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-pubsub-client = { workspace = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
