[package]
name = "gorbagana-runtime-transaction"
description = "Gorbagana runtime-transaction"
documentation = "https://docs.rs/gorbagana-runtime-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_runtime_transaction"

[features]
dev-context-only-utils = ["gorbagana-compute-budget-instruction/dev-context-only-utils"]

[dependencies]
agave-transaction-view = { workspace = true }
log = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-compute-budget-instruction = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-message = { workspace = true, features = ["blake3"] }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-svm-transaction = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
bincode = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
gorbagana-compute-budget-instruction = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-compute-budget-interface = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true, features = ["bincode"] }
gorbagana-system-transaction = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["blake3"] }
gorbagana-vote-interface = { workspace = true }

[[bench]]
name = "get_signature_details"
harness = false

[lints]
workspace = true
