[package]
name = "gorbagana-vortexor"
description = "Gorbagana TPU Vortexor"
documentation = "https://docs.rs/gorbagana-vortexor"
default-run = "gorbagana-vortexor"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_vortexor"

[dependencies]
agave-banking-stage-ingress-types = { workspace = true }
async-channel = { workspace = true }
bytes = { workspace = true }
clap = { version = "4.5.31", features = ["cargo", "derive", "error-context"] }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
futures  = { workspace = true }
futures-util = { workspace = true }
governor = { workspace = true }
histogram = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
nix = { workspace = true, features = ["net"] }
pem = { workspace = true }
percentage = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rand = { workspace = true }
rustls = { workspace = true }
signal-hook = { workspace = true }
smallvec = { workspace = true }
socket2 = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-core = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-perf = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-transaction-metrics-tracker = { workspace = true }
gorbagana-version = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
gorbagana-local-cluster = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
