[package]
name = "gorbagana-download-utils"
description = "Gorbagana Download Utils"
documentation = "https://docs.rs/gorbagana-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_download_utils"

[dependencies]
log = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-file-download = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-runtime = { workspace = true }

[dev-dependencies]
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
