[package]
name = "gorbagana-svm-transaction"
description = "Gorbagana SVM Transaction"
documentation = "https://docs.rs/gorbagana-svm-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
gorbagana-hash = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-transaction = { workspace = true }

[dev-dependencies]
gorbagana-message = { workspace = true, features = ["bincode"] }
gorbagana-nonce = { workspace = true }
gorbagana-system-interface = { workspace = true }
static_assertions = { workspace = true }
test-case = { workspace = true }
