[package]
name = "gorbagana-pubsub-client"
description = "Gorbagana Pubsub Client"
documentation = "https://docs.rs/gorbagana-pubsub-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
log = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder-client-types = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client-types = { workspace = true }
gorbagana-signature = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
url = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
