[package]
name = "gorbagana-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
agave-feature-set = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-cli-output = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-cluster-type = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-core = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-feature-gate-interface = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-geyser-plugin-manager = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true }
gorbagana-logger = "=2.3.1"
gorbagana-message = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-program-test = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rpc = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-validator-exit = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
gorbagana-sdk-ids = { workspace = true }
