[package]
name = "agave-install"
description = "The gorbagana cluster software installer"
documentation = "https://docs.rs/agave-install"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atty = { workspace = true }
bincode = { workspace = true }
bzip2 = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
dirs-next = { workspace = true }
indicatif = { workspace = true }
nix = { workspace = true, features = ["signal"] }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
scopeguard = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_yaml = { workspace = true }
serde_yaml_08 = { package = "serde_yaml", version = "0.8.26" }
gorbagana-clap-utils = { workspace = true }
gorbagana-config-interface = "=1.0.0"
gorbagana-config-program-client = { version = "=1.1.0", features = ["serde"] }
gorbagana-hash = "=2.3.0"
gorbagana-keypair = "=2.2.1"
gorbagana-logger = "=2.3.1"
gorbagana-message = "=2.4.0"
gorbagana-pubkey = { version = "=2.4.0", default-features = false }
gorbagana-rpc-client = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-signature = { version = "=2.3.0", default-features = false }
gorbagana-signer = "=2.2.1"
gorbagana-transaction = "=2.2.3"
gorbagana-version = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }

[target."cfg(windows)".dependencies]
winapi = { workspace = true, features = ["minwindef", "winuser"] }
winreg = { workspace = true }
