[package]
name = "json-rpc-client"
description = "Reference example using Gorbagana SVM API for RPC API"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
borsh = { workspace = true }
clap = { workspace = true }
home = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-transaction = { workspace = true }
thiserror = { workspace = true }
yaml-rust = { workspace = true }
