[package]
name = "agave-accounts-hash-cache-tool"
description = "Tool for accounts hash cache files"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = []

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
memmap2 = { workspace = true }
rayon = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-version = { workspace = true }
