[package]
name = "gorbagana-rpc-test"
description = "Gorbagana RPC Test"
documentation = "https://docs.rs/gorbagana-rpc-test"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-pubsub-client = { workspace = true }
gorbagana-rpc = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-test-validator = { workspace = true }
gorbagana-tpu-client = { workspace = true }
gorbagana-transaction-status = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-transaction = { workspace = true }
gorbagana-transaction = { workspace = true }
