[package]
name = "agave-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/agave-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
dev-context-only-utils = []

[dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
pretty-hex = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account  = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-clap-utils = { workspace = true }
gorbagana-cli-output = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-core = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-cost-model = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-feature-gate-interface = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-geyser-plugin-manager = { workspace = true }
gorbagana-gossip = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-inflation = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-ledger = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-loader-v3-interface = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-logger = "=2.3.1"
gorbagana-measure = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["metrics"] }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-rpc = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-runtime-transaction = { workspace = true }
gorbagana-sbpf = { workspace = true, features = ["debugger"] }
gorbagana-sdk-ids = { workspace = true }
gorbagana-shred-version = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-stake-program = { workspace = true }
gorbagana-storage-bigtable = { workspace = true }
gorbagana-streamer = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-status = { workspace = true }
gorbagana-type-overrides = { workspace = true }
gorbagana-unified-scheduler-pool = { workspace = true }
gorbagana-version = { workspace = true }
gorbagana-vote = { workspace = true }
gorbagana-vote-program = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(any(target_env = "msvc", target_os = "freebsd")))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
