[package]
name = "gorbagana-svm-example-paytube"
description = "Reference example using Gorbagana SVM API"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
agave-feature-set = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bpf-loader-program = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-fee-structure = "=2.3.0"
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-program-pack = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true }
gorbagana-rent-collector = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-program = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["blake3"] }
gorbagana-transaction-error = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }
termcolor = { workspace = true }

[dev-dependencies]
gorbagana-test-validator = { workspace = true }
