[package]
name = "gorbagana-storage-bigtable"
description = "Gorbagana Storage BigTable"
documentation = "https://docs.rs/gorbagana-storage-bigtable"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_storage_bigtable"

[dependencies]
agave-reserved-account-keys = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
bincode = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
enum-iterator = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
goauth = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-proxy = { workspace = true }
log = { workspace = true }
# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
openssl = { workspace = true, features = ["vendored"] }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
smpl_jwt = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-serde = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-storage-proto = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport"] }
zstd = { workspace = true }

[dev-dependencies]
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-system-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
