[package]
description = "Gorbagana Program Test Framework"
name = "gorbagana-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-info = { workspace = true }
gorbagana-accounts-db = { workspace = true }
gorbagana-banks-client = { workspace = true }
gorbagana-banks-interface = { workspace = true }
gorbagana-banks-server = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-epoch-rewards = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-loader-v3-interface = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-msg = { workspace = true }
gorbagana-native-token = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-program-entrypoint = { workspace = true }
gorbagana-program-error = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-sbpf = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-stable-layout = { workspace = true }
gorbagana-stake-interface = { workspace = true }
gorbagana-svm = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-sysvar = { workspace = true }
gorbagana-sysvar-id = { workspace = true }
gorbagana-timings = { workspace = true }
gorbagana-transaction = { workspace = true }
gorbagana-transaction-context = { workspace = true }
gorbagana-transaction-error = { workspace = true }
gorbagana-vote-program = { workspace = true }
spl-generic-token = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
gorbagana-cpi = { workspace = true }
gorbagana-program = { workspace = true }
gorbagana-stake-program = { workspace = true }
test-case = { workspace = true }
