[package]
name = "gorbagana-rpc-client-nonce-utils"
description = "Gorbagana RPC Client Nonce Utilities"
documentation = "https://docs.rs/gorbagana-rpc-client-nonce-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = []
clap = ["dep:clap", "dep:gorbagana-clap-utils"]

[dependencies]
clap = { version = "2.33.0", optional = true }
gorbagana-account = { workspace = true, features = ["bincode"] }
gorbagana-clap-utils = { workspace = true, optional = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-nonce = { workspace = true, features = ["serde"] }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-transaction = { workspace = true }
tokio = { workspace = true, features = ["full"] }
