[package]
name = "gorbagana-rpc-client"
description = "Gorbagana RPC Client"
documentation = "https://docs.rs/gorbagana-rpc-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["spinner"]
# Support rpc-client methods that feature a spinner progress bar for
# command-line interfaces
spinner = ["dep:indicatif"]

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true, optional = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
reqwest-middleware = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-account-decoder-client-types = { workspace = true, features = ["zstd"] }
gorbagana-clock = { workspace = true }
gorbagana-commitment-config = { workspace = true }
gorbagana-epoch-info = { workspace = true, features = ["serde"] }
gorbagana-epoch-schedule = { workspace = true, features = ["serde"] }
gorbagana-feature-gate-interface = { workspace = true, features = ["serde"] }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-message = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-rpc-client-api = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["bincode"] }
gorbagana-transaction-error = { workspace = true }
gorbagana-transaction-status-client-types = { workspace = true }
gorbagana-version = { workspace = true }
gorbagana-vote-interface = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
futures = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-http-server = { workspace = true }
gorbagana-account-decoder = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-signer = { workspace = true }
gorbagana-system-transaction = { workspace = true }
static_assertions = { workspace = true }
