[package]
name = "gorbagana-zk-keygen"
description = """
Gorbagana privacy-related key generation utility

The tool currently supports two types of encryption keys that are used in the SPL Token-2022 program:
  - ElGamal keypair that can be used for public key encryption
  - AES128 key that can be used for an authenticated symmetric encryption (e.g. AES-GCM-SIV)
"""
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "gorbagana-zk-keygen"
path = "src/main.rs"

[dependencies]
bs58 = { workspace = true }
clap = { version = "3.1.5", features = ["cargo", "derive"] }
dirs-next = { workspace = true }
gorbagana-clap-v3-utils = { workspace = true }
gorbagana-remote-wallet = { workspace = true, features = ["default"] }
gorbagana-seed-derivable = "=2.2.1"
gorbagana-signer = "=2.2.1"
gorbagana-version = { workspace = true }
gorbagana-zk-token-sdk = { workspace = true }
thiserror = { workspace = true }
tiny-bip39 = { workspace = true }

[dev-dependencies]
gorbagana-pubkey = { workspace = true, features = ["rand"] }
tempfile = { workspace = true }
