[package]
name = "gorbagana-system-program"
description = "Gorbagana System program"
documentation = "https://docs.rs/gorbagana-system-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_system_program"

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bincode = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-log-collector = { workspace = true }
gorbagana-nonce = { workspace = true, features = ["serde"] }
gorbagana-nonce-account = { workspace = true }
gorbagana-packet = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["sha2"] }
gorbagana-sdk-ids = { workspace = true }
gorbagana-system-interface = { workspace = true, features = ["serde"] }
gorbagana-sysvar = { workspace = true }
gorbagana-transaction-context = { workspace = true, features = ["bincode"] }
gorbagana-type-overrides = { workspace = true }

[dev-dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
criterion = { workspace = true }
gorbagana-compute-budget = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-nonce-account = { workspace = true }
gorbagana-rent = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-svm-callback = { workspace = true }
gorbagana-svm-feature-set = { workspace = true }

[[bench]]
name = "system"
harness = false
