[package]
name = "gorbagana-send-transaction-service"
description = "Gorbagana send transaction service"
documentation = "https://docs.rs/gorbagana-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
dev-context-only-utils = ["gorbagana-net-utils"]

[dependencies]
async-trait = { workspace = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
gorbagana-client = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-connection-cache = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-net-utils = { workspace = true, optional = true }
gorbagana-nonce-account = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-quic-definitions = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-signature = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-tpu-client-next = { workspace = true, features = ["metrics"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }

[dev-dependencies]
gorbagana-account = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-genesis-config = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-net-utils = { workspace = true }
gorbagana-nonce = { workspace = true }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-signer = { workspace = true }
gorbagana-system-interface = { workspace = true }
gorbagana-system-transaction = { workspace = true }
