[package]
name = "gorbagana-poh"
description = "Gorbagana PoH"
documentation = "https://docs.rs/gorbagana-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_poh"

[features]
dev-context-only-utils = []

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
qualifier_attr = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-entry = { workspace = true }
gorbagana-hash = { workspace = true }
gorbagana-ledger = { workspace = true }
gorbagana-measure = { workspace = true }
gorbagana-metrics = { workspace = true }
gorbagana-poh-config = { workspace = true }
gorbagana-pubkey = { workspace = true }
gorbagana-runtime = { workspace = true }
gorbagana-time-utils = { workspace = true }
gorbagana-transaction = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-perf = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-poh = { path = ".", features = ["dev-context-only-utils"] }
gorbagana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-system-transaction = { workspace = true }

[[bench]]
name = "poh"

[[bench]]
name = "transaction_recorder"
harness = false
