[package]
name = "gorbagana-vote-program"
description = "Gorbagana Vote program"
documentation = "https://docs.rs/gorbagana-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "gorbagana_vote_program"

[features]
default = ["metrics"]
frozen-abi = [
    "dep:gorbagana-frozen-abi",
    "dep:gorbagana-frozen-abi-macro",
    "gorbagana-program-runtime/frozen-abi",
    "gorbagana-vote-interface/frozen-abi",
]
metrics = ["dep:gorbagana-metrics"]

[dependencies]
agave-feature-set = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-bincode = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-epoch-schedule = { workspace = true }
gorbagana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
gorbagana-hash = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-keypair = { workspace = true }
gorbagana-metrics = { workspace = true, optional = true }
gorbagana-packet = { workspace = true }
gorbagana-program-runtime = { workspace = true }
gorbagana-pubkey = { workspace = true, features = ["curve25519"] }
gorbagana-rent = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-signer = { workspace = true }
gorbagana-slot-hashes = { workspace = true }
gorbagana-transaction = { workspace = true, features = ["bincode"] }
gorbagana-transaction-context = { workspace = true, features = ["bincode"] }
gorbagana-vote-interface = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
gorbagana-account = { workspace = true }
gorbagana-clock = { workspace = true }
gorbagana-fee-calculator = { workspace = true }
gorbagana-instruction = { workspace = true }
gorbagana-logger = { workspace = true }
gorbagana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
gorbagana-pubkey = { workspace = true, features = ["rand"] }
gorbagana-rent = { workspace = true }
gorbagana-sdk-ids = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "vote_instructions"
harness = false

[lints]
workspace = true
