[package]
name = "gorbagana-metrics"
description = "Gorbagana Metrics"
documentation = "https://docs.rs/gorbagana-metrics"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "gorbagana_metrics"

[dependencies]
crossbeam-channel = { workspace = true }
gethostname = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
gorbagana-cluster-type = { workspace = true }
gorbagana-sha256-hasher = { workspace = true }
gorbagana-time-utils = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }

[[bench]]
name = "metrics"
